// Code generated by go generate; DO NOT EDIT.
// +build linux_bpf

package runtime

var Conntrack = NewRuntimeAsset("conntrack.c", "d4a94d0b2ca8aa79f1451e6bb9b4206357f77f003330efe762cd1dd4620fed88")
