// Code generated by go generate; DO NOT EDIT.
// +build linux_bpf

package runtime

var RuntimeSecurity = NewRuntimeAsset("runtime-security.c", "ecf0c65f2001ba63a5543b3f5323bcf158c7533d5600ad6e37722788e3cfa7ee")
