// Code generated by go generate; DO NOT EDIT.
// +build linux_bpf

package runtime

var RuntimeSecurity = NewRuntimeAsset("runtime-security.c", "a2eca4f0854bb50f3b08e05acd9716c4854db95cd0929d7a9a738135eb5a6258")
