// Code generated by go generate; DO NOT EDIT.
// +build linux_bpf

package runtime

var RuntimeSecurity = NewRuntimeAsset("runtime-security.c", "b181f59343bd0699dcfa051ee5f64f8b6584f4578e06ad939a0ef94774ccec79")
